local assert = require("utils").assert

local types = {}
for type_id, type in pairs(node.types()) do
  if type_id ~= 8 then
    types[type] = {}
    for field_id, field in pairs(node.fields(type_id)) do
      types[type][field_id] = field
    end
  end
end

assert.same(types, {
  accent = {
    "id",
    "subtype",
    "attr",
    "nucleus",
    "sub",
    "sup",
    "accent",
    "bot_accent",
    "top_accent",
    "overlay_accent",
    "fraction",
    [-1] = "prev",
    [0] = "next",
  },
  adjust = {
    "id",
    "subtype",
    "attr",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  align_record = { "id", "subtype", [-1] = "prev", [0] = "next" },
  align_stack = { "id", "subtype", [-1] = "prev", [0] = "next" },
  attribute = { "id", "number", "value", [0] = "next" },
  attribute_list = { "id", [0] = "next" },
  boundary = {
    "id",
    "subtype",
    "attr",
    "value",
    [-1] = "prev",
    [0] = "next",
  },
  choice = {
    "id",
    "subtype",
    "attr",
    "display",
    "text",
    "script",
    "scriptscript",
    [-1] = "prev",
    [0] = "next",
  },
  delim = {
    "id",
    "subtype",
    "attr",
    "small_fam",
    "small_char",
    "large_fam",
    "large_char",
    [-1] = "prev",
    [0] = "next",
  },
  delta = { "id", "subtype", [-1] = "prev", [0] = "next" },
  dir = {
    "id",
    "subtype",
    "attr",
    "dir",
    "level",
    [-1] = "prev",
    [0] = "next",
  },
  disc = {
    "id",
    "subtype",
    "attr",
    "pre",
    "post",
    "replace",
    "penalty",
    [-1] = "prev",
    [0] = "next",
  },
  expr_stack = { "id", "subtype", [-1] = "prev", [0] = "next" },
  fence = {
    "id",
    "subtype",
    "attr",
    "delim",
    "italic",
    "height",
    "depth",
    "options",
    "class",
    [-1] = "prev",
    [0] = "next",
  },
  fraction = {
    "id",
    "subtype",
    "attr",
    "width",
    "num",
    "denom",
    "left",
    "right",
    "middle",
    "fam",
    "options",
    [-1] = "prev",
    [0] = "next",
  },
  glue = {
    "id",
    "subtype",
    "attr",
    "leader",
    "width",
    "stretch",
    "shrink",
    "stretch_order",
    "shrink_order",
    [-1] = "prev",
    [0] = "next",
  },
  glue_spec = {
    "id",
    "width",
    "stretch",
    "shrink",
    "stretch_order",
    "shrink_order",
    [0] = "next",
  },
  glyph = {
    "id",
    "subtype",
    "attr",
    "char",
    "font",
    "lang",
    "left",
    "right",
    "uchyph",
    "components",
    "xoffset",
    "yoffset",
    "width",
    "height",
    "depth",
    "expansion_factor",
    "data",
    [-1] = "prev",
    [0] = "next",
  },
  hlist = {
    "id",
    "subtype",
    "attr",
    "width",
    "depth",
    "height",
    "dir",
    "shift",
    "glue_order",
    "glue_sign",
    "glue_set",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  hyphenated = { "id", "subtype", [-1] = "prev", [0] = "next" },
  if_stack = { "id", "subtype", [-1] = "prev", [0] = "next" },
  ins = {
    "id",
    "subtype",
    "attr",
    "cost",
    "depth",
    "height",
    "spec",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  kern = {
    "id",
    "subtype",
    "attr",
    "kern",
    "expansion_factor",
    [-1] = "prev",
    [0] = "next",
  },
  local_par = {
    "id",
    "subtype",
    "attr",
    "pen_inter",
    "pen_broken",
    "dir",
    "box_left",
    "box_left_width",
    "box_right",
    "box_right_width",
    [-1] = "prev",
    [0] = "next",
  },
  margin_kern = {
    "id",
    "subtype",
    "attr",
    "width",
    "glyph",
    [-1] = "prev",
    [0] = "next",
  },
  mark = {
    "id",
    "subtype",
    "attr",
    "class",
    "mark",
    [-1] = "prev",
    [0] = "next",
  },
  math = {
    "id",
    "subtype",
    "attr",
    "surround",
    "width",
    "stretch",
    "shrink",
    "stretch_order",
    "shrink_order",
    [-1] = "prev",
    [0] = "next",
  },
  math_char = {
    "id",
    "subtype",
    "attr",
    "fam",
    "char",
    [-1] = "prev",
    [0] = "next",
  },
  math_text_char = {
    "id",
    "subtype",
    "attr",
    "fam",
    "char",
    [-1] = "prev",
    [0] = "next",
  },
  movement_stack = { "id", "subtype", [-1] = "prev", [0] = "next" },
  nested_list = { "id", "subtype", [-1] = "prev", [0] = "next" },
  noad = {
    "id",
    "subtype",
    "attr",
    "nucleus",
    "sub",
    "sup",
    [-1] = "prev",
    [0] = "next",
  },
  page_insert = {
    "id",
    "subtype",
    "height",
    "last_ins_ptr",
    "best_ins_ptr",
    "width",
    "stretch",
    "shrink",
    "stretch_order",
    "shrink_order",
    [-1] = "prev",
    [0] = "next",
  },
  passive = { "id", "subtype", [-1] = "prev", [0] = "next" },
  penalty = {
    "id",
    "subtype",
    "attr",
    "penalty",
    [-1] = "prev",
    [0] = "next",
  },
  pseudo_file = { "id", "subtype", [-1] = "prev", [0] = "next" },
  pseudo_line = { "id", "subtype", [-1] = "prev", [0] = "next" },
  radical = {
    "id",
    "subtype",
    "attr",
    "nucleus",
    "sub",
    "sup",
    "left",
    "degree",
    "width",
    "options",
    [-1] = "prev",
    [0] = "next",
  },
  rule = {
    "id",
    "subtype",
    "attr",
    "width",
    "depth",
    "height",
    "dir",
    "index",
    "left",
    "right",
    [-1] = "prev",
    [0] = "next",
  },
  shape = { "id", "subtype", [-1] = "prev", [0] = "next" },
  span = { "id", "subtype", [-1] = "prev", [0] = "next" },
  split_insert = {
    "id",
    "subtype",
    "height",
    "last_ins_ptr",
    "best_ins_ptr",
    "broken_ptr",
    "broken_ins",
    [-1] = "prev",
    [0] = "next",
  },
  style = {
    "id",
    "subtype",
    "attr",
    "style",
    [-1] = "prev",
    [0] = "next",
  },
  sub_box = {
    "id",
    "subtype",
    "attr",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  sub_mlist = {
    "id",
    "subtype",
    "attr",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  temp = { "id", "subtype", [-1] = "prev", [0] = "next" },
  unhyphenated = { "id", "subtype", [-1] = "prev", [0] = "next" },
  unset = {
    "id",
    "subtype",
    "attr",
    "width",
    "depth",
    "height",
    "dir",
    "shrink",
    "glue_order",
    "glue_sign",
    "stretch",
    "span",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
  vlist = {
    "id",
    "subtype",
    "attr",
    "width",
    "depth",
    "height",
    "dir",
    "shift",
    "glue_order",
    "glue_sign",
    "glue_set",
    "head",
    [-1] = "prev",
    [0] = "next",
  },
})
