local assert = require("utils").assert

local function equals(name, id)
  assert.equals(node.id(name), id)
end

equals("hlist", 0)
equals("vlist", 1)
equals("rule", 2)
equals("ins", 3)
equals("mark", 4)
equals("adjust", 5)
equals("boundary", 6)
equals("disc", 7)
equals("whatsit", 8)
equals("local_par", 9)
equals("dir", 10)
equals("math", 11)
equals("glue", 12)
equals("kern", 13)
equals("penalty", 14)
equals("unset", 15)
equals("style", 16)
equals("choice", 17)
equals("noad", 18)
equals("radical", 19)
equals("fraction", 20)
equals("accent", 21)
equals("fence", 22)
equals("math_char", 23)
equals("sub_box", 24)
equals("sub_mlist", 25)
equals("math_text_char", 26)
equals("delim", 27)
equals("margin_kern", 28)
equals("glyph", 29)
equals("align_record", 30)
equals("pseudo_file", 31)
equals("pseudo_line", 32)
equals("page_insert", 33)
equals("split_insert", 34)
equals("expr_stack", 35)
equals("nested_list", 36)
equals("span", 37)
equals("attribute", 38)
equals("glue_spec", 39)
equals("attribute_list", 40)
equals("temp", 41)
equals("align_stack", 42)
equals("movement_stack", 43)
equals("if_stack", 44)
equals("unhyphenated", 45)
equals("hyphenated", 46)
equals("delta", 47)
equals("passive", 48)
equals("shape", 49)
