local assert = require("utils").assert

local function equals(name, id)
  assert.equals(node.subtype(name), id)
end

equals("open", 0)
equals("write", 1)
equals("close", 2)
equals("special", 3)
equals("late_special", 4)
equals("save_pos", 7)
equals("late_lua", 8)
equals("user_defined", 9)
equals("pdf_literal", 16)
equals("pdf_late_literal", 17)
equals("pdf_refobj", 18)
equals("pdf_annot", 19)
equals("pdf_start_link", 20)
equals("pdf_end_link", 21)
equals("pdf_dest", 22)
equals("pdf_action", 23)
equals("pdf_thread", 24)
equals("pdf_start_thread", 25)
equals("pdf_end_thread", 26)
equals("pdf_thread_data", 27)
equals("pdf_link_data", 28)
equals("pdf_colorstack", 29)
equals("pdf_setmatrix", 30)
equals("pdf_save", 31)
equals("pdf_restore", 32)
equals("pdf_link_state", 33)
