local assert = require("utils").assert

assert.same(node.whatsits(), {
  [0] = "open",
  [1] = "write",
  [2] = "close",
  [3] = "special",
  [4] = "late_special",
  [7] = "save_pos",
  [8] = "late_lua",
  [9] = "user_defined",
  [16] = "pdf_literal",
  [17] = "pdf_late_literal",
  [18] = "pdf_refobj",
  [19] = "pdf_annot",
  [20] = "pdf_start_link",
  [21] = "pdf_end_link",
  [22] = "pdf_dest",
  [23] = "pdf_action",
  [24] = "pdf_thread",
  [25] = "pdf_start_thread",
  [26] = "pdf_end_thread",
  [27] = "pdf_thread_data",
  [28] = "pdf_link_data",
  [29] = "pdf_colorstack",
  [30] = "pdf_setmatrix",
  [31] = "pdf_save",
  [32] = "pdf_restore",
  [33] = "pdf_link_state",
})
