---% language=uk
---
---\environment luatex-style
---
---\startcomponent luatex-statistics
---
---# Statistics
---
---    
---
---    The following fonts are used in this document:
---
---    \showfontusage
---
---\stopchapter
---
---\stopcomponent
---