---\startcomponent luatex-firstpage
---
---\startstandardmakeup
---
---    \start
---        \raggedleft
---        \definedfont[Bold*default at 48pt]
---        \setupinterlinespace
---        \blue \documentvariable{manual} \endgraf Reference \endgraf Manual \endgraf
---    \stop
---
---    \vfill
---
---    \definedfont[Bold*default at 12pt]
---
---    
---         copyright \EQ Lua\TeX\ development team 
---         more info \EQ www.luatex.org 
---         version   \EQ \currentdate \doifsomething{\documentvariable{snapshot}}{(snapshot \documentvariable{snapshot})} 
---    
---
---\stopstandardmakeup
---
---\setupbackgrounds
---  [leftpage]
---  [setups=pagenumber:left]
---
---\setupbackgrounds
---  [rightpage]
---  [setups=pagenumber:right]
---
---\stopcomponent
---