local assert = require("utils").assert

assert.node_type("glue", nil, {
  id = "glue (12)",
  subtypes = {
    "userskip (0)",
    "lineskip (1)",
    "baselineskip (2)",
    "parskip (3)",
    "abovedisplayskip (4)",
    "belowdisplayskip (5)",
    "abovedisplayshortskip (6)",
    "belowdisplayshortskip (7)",
    "leftskip (8)",
    "rightskip (9)",
    "topskip (10)",
    "splittopskip (11)",
    "tabskip (12)",
    "spaceskip (13)",
    "xspaceskip (14)",
    "parfillskip (15)",
    "mathskip (16)",
    "thinmuskip (17)",
    "medmuskip (18)",
    "thickmuskip (19)",
    "conditionalmathskip (98)",
    "muglue (99)",
    "leaders (100)",
  },
  fields = {
    "prev (-1)",
    "next (0)",
    "id (1)",
    "subtype (2)",
    "attr (3)",
    "leader (4)",
    "width (5)",
    "stretch (6)",
    "shrink (7)",
    "stretch_order (8)",
    "shrink_order (9)",
  },
})
