local assert = require("utils").assert

assert.node_type("hlist", nil, {
  id = "hlist (0)",
  subtypes = {
    "unknown (0)",
    "line (1)",
    "box (2)",
    "indent (3)",
    "alignment (4)",
    "cell (5)",
    "equation (6)",
    "equationnumber (7)",
    "math (8)",
    "mathchar (9)",
    "hextensible (10)",
    "vextensible (11)",
    "hdelimiter (12)",
    "vdelimiter (13)",
    "overdelimiter (14)",
    "underdelimiter (15)",
    "numerator (16)",
    "denominator (17)",
    "limits (18)",
    "fraction (19)",
    "nucleus (20)",
    "sup (21)",
    "sub (22)",
    "degree (23)",
    "scripts (24)",
    "over (25)",
    "under (26)",
    "accent (27)",
    "radical (28)",
  },
  fields = {
    "prev (-1)",
    "next (0)",
    "id (1)",
    "subtype (2)",
    "attr (3)",
    "width (4)",
    "depth (5)",
    "height (6)",
    "dir (7)",
    "shift (8)",
    "glue_order (9)",
    "glue_sign (10)",
    "glue_set (11)",
    "head (12)",
  },
})
