---% language=us runpath=texruns:manuals/luametatex
---
---\environment luametatex-style
---
---\startcomponent luametatex-firstpage
---
---\startstandardmakeup
---
---    \start
---        \raggedleft
---        \definedfont[Bold*default at 48pt]
---        \setupinterlinespace
---        \blue \documentvariable{manual} \endgraf Reference \endgraf Manual \endgraf
---    \stop
---
---    \vfill
---
---    \definedfont[Bold*default at 12pt]
---
---    
---         copyright \EQ LuaMeta\TeX\ development team  \EQ Lua\TeX\ development team  \EQ *ConTeXt* development team 
---         more info \EQ www.luatex.org  \EQ contextgarden.net  \EQ build.contextgarden.net 
---         version   \EQ \currentdate \doifsomething{\documentvariable{snapshot}}{(snapshot \documentvariable{snapshot})} 
---    
---
---\stopstandardmakeup
---
---\setupbackgrounds
---  [leftpage]
---  [setups=pagenumber:left]
---
---\setupbackgrounds
---  [rightpage]
---  [setups=pagenumber:right]
---
---\stopcomponent
---