---% language=us runpath=texruns:manuals/luametatex
---
---\environment luametatex-style
---
---\startcomponent luametatex-registers
---
---\startchapter[title=Topics]
---
---    \placeregister[topicindex]
---
---\stopchapter
---
---\startchapter[title=Primitives]
---
---    This register contains the primitives that are mentioned in the manual. There
---    are of course many more primitives. The \ETEX\ and *LuaTeX* primitives are
---    typeset in bold (some originate in *PDF*TEX).
---
---   %\placeregister[primitiveindex][indicator=no]
---    \placeregister[texindex,etexindex,luatexindex][indicator=no]
---
---\stopchapter
---
---\startchapter[title=Callbacks]
---
---    \placeregister[callbackindex]
---
---\stopchapter
---
---\startchapter[title=Nodes]
---
---    This register contains the nodes that are known to *LuaTeX*. The primary nodes
---    are in bold, whatsits that are determined by their subtype are normal.
---
---    \placeregister[nodeindex]
---
---\stopchapter
---
---\startchapter[title=Libraries]
---
---    This register contains the functions available in libraries. Not all functions
---    are documented, for instance because they can be experimental or obsolete.
---
---    \placeregister[libraryindex]
---
---\stopchapter
---
---\stopcomponent
---